CREATE MEMORY TABLE PROGRAMMING(PNO INT NOT NULL PRIMARY KEY,WRITER VARCHAR(50),SUBJECT VARCHAR(50),CONTENTS VARCHAR(1000),NOWDATE VARCHAR(10))
INSERT INTO PROGRAMMING VALUES(1,'tj','test','test 입니다', date);
INSERT INTO PROGRAMMING VALUES(2,'tj1','test1','test 입니다', date);
INSERT INTO PROGRAMMING VALUES(3,'tj2','test2','test 입니다', date);
INSERT INTO PROGRAMMING VALUES(4,'tj3','test3','test 입니다', date);
INSERT INTO PROGRAMMING VALUES(5,'tj4','test4','test 입니다', date);
INSERT INTO PROGRAMMING VALUES(6,'tj5','test5','test 입니다', date);
INSERT INTO PROGRAMMING VALUES(7,'tj6','test6','test 입니다', date);
INSERT INTO PROGRAMMING VALUES(8,'tj7','test7','test 입니다', date);
INSERT INTO PROGRAMMING VALUES(9,'tj8','test8','test 입니다', date);
INSERT INTO PROGRAMMING VALUES(10,'tj9','test9','test 입니다', date);